from pathlib import Path
import json

P=Path(__file__).resolve().parent
texts={
'cold_open':"Manchester United have already proved Michael Carrick can fix them. That is what makes this start so alarming. He arrived in January, simplified the shape, lifted the team to third, and earned a permanent deal. Four months later, United had five points from five league games, lost to promoted Hull, lost at home to a Manchester City side reduced to ten men, and threw away a two-goal lead against Brighton in the League Cup. So what disappeared? Maybe nothing. Maybe the first recovery was real, but it only solved the easiest problem. Carrick gave United clarity. Now he has to build an identity that survives when the game stops looking comfortable.",
'rescue_real':"Start with the evidence Carrick earned. He took over on 13 January after Ruben Amorim left and Darren Fletcher covered the following week. United collected thirty-nine league points from then to the finish, the best total in the division over that span, and ended third. It was not a miracle. It was a correction. Carrick returned the team to a flexible 4-2-3-1, put players in recognisable zones, moved Bruno Fernandes closer to the forward line, and defended in a compact 4-4-2. Imagine you are a centre-back facing them. If you step forward, United can release runners into the space behind you. If you sit off, Bruno can receive between your midfield and defence. The football became simpler, and confidence followed. That is a coaching achievement, not an illusion.",
'where_breaks':"But a transition system depends on the opponent giving you somewhere to transition into. When the other team advances, Carrick's United can compress the centre, win the next ball, and attack before the block resets. When the opponent sits deeper, the picture changes. United need repeatable possession patterns: a full-back who knows when to advance, a midfielder who protects the counter, and a front four who create width without abandoning the centre. Early this season, those relationships have looked improvised. The attackers can become too high and too wide. Bruno and Matheus Cunha roam toward the ball. The double pivot is asked to cover an enormous pitch. One lost pass, and the back line is defending a race rather than a structure.",
'warning_week':"The scorelines matter because each exposed a different game state. Everton equalised in the ninety-sixth minute after United had led twice. Manchester City won one-nil at Old Trafford despite playing with ten men from the twenty-third minute. Brighton turned a two-nil deficit into a three-two cup win. Then Fulham outran United by 6.6 kilometres and United needed a deflected eighty-ninth-minute equaliser for a one-one draw. That is not one tactical flaw repeated four times. It is a team failing four different tests: protecting a lead, breaking down ten men, controlling chaos, and matching an opponent's energy. A formation can organise the first whistle. It cannot make the correct decision for ninety minutes.",
'tactical_dilemma':"The popular answer is to change shape. Add another midfielder. Pull the wingers narrower. Give the full-backs more protection. Those changes may help, but every solution charges a price. More control can isolate the striker. More attacking freedom can expose the double pivot. Push both full-backs and a turnover opens the channels behind them. Keep one at home and the low block becomes harder to stretch. Carrick's best United has lived between order and speed. The current version too often chooses neither: cautious circulation without rest-defence, then desperate attacks without compact pressure behind the ball. The task is not finding one perfect formation. It is teaching the same principles to survive every formation.",
'club_cannot_hide':"There is a tempting excuse: Carrick inherited a squad assembled for incompatible managers. That is partly true. But it is no longer the whole truth. United gave him a contract through 2028. The hierarchy led by Omar Berrada and Jason Wilcox rebuilt the midfield with Andrey Santos, Youri Tielemans and Carlos Baleba. Carrick now owns part of the solution and part of the problem. A modern football structure should recruit for principles that outlast the coach: how the team builds, presses, protects the centre, and responds after losing the ball. If those principles are clear, a new manager adjusts the model. If they are not, every appointment becomes demolition followed by another expensive rebuild.",
'conclusion':"So, is Carrick failing? Five league games cannot erase what he achieved across seventeen last season. United also returned to the Champions League with a four-nil win over Sabah. The honest verdict is harder: Carrick solved the first problem, clarity, and has now met the second, repeatability. His team can punish space. It has not proved it can create against caution, defend after its own attacks, or sustain collective intensity when momentum turns. Sacking him would not answer those questions. Protecting him from them would be just as dangerous. Manchester United do not need another saviour with a new diagram. They need Carrick and the hierarchy to make one football idea survive bad form, different opponents, and the next transfer window. Until that happens, every rebuild will keep looking like progress right before the next reset."}
live=['Qiob0M7_kCI.mp4','WFWdZX7QZDc.mp4','vqiU8yTPqQs.mp4','Kawuk_LevLw.mp4','zseiHM5FtVA.mp4','4Oeu-tOvXcE.mp4','0Pmw4s8w-O0.mp4','wppwUeYVQXo.mp4']
tactics=['tactics_compact_442.mp4','tactics_transition_release.mp4','tactics_low_block_problem.mp4','tactics_right_overload.mp4','tactics_rest_defence_gap.mp4','tactics_game_state_balance.mp4']
def shots(section,seed):
 out=[]
 for i in range(15):
  f=tactics[(seed+i)%len(tactics)] if i in (3,8,12) else live[(seed+i)%len(live)]
  start=0 if f.startswith('tactics_') else 18+((seed*37+i*29)%210)
  out.append({'file':'assets/broll/'+f,'start':start,'duration':4.2,'label':f'{section}_{i:02d}'})
 return out
order=['cold_open','rescue_real','where_breaks','warning_week','tactical_dilemma','club_cannot_hide','conclusion']
sections=[]
for i,name in enumerate(order):
 sections.append({'type':'vo','name':name,'text':texts[name],'broll':shots(name,i)})
 if name=='cold_open':sections.append({'type':'insert','name':'neville_experiments','file':'assets/broll/neville_experiments.mp4','start':328.56,'end':352.8})
 if name=='where_breaks':sections.append({'type':'insert','name':'carrick_accountability','file':'assets/broll/Qiob0M7_kCI.mp4','start':24.0,'end':40.0})
 if name=='tactical_dilemma':sections.append({'type':'insert','name':'carrick_before_derby','file':'assets/broll/WFWdZX7QZDc.mp4','start':62.0,'end':77.0})
cfg={'schema_version':1,'title':'Why Every Manchester United Rebuild Fails','output_filename':'why-every-manchester-united-rebuild-fails.mp4','thumbnail':'assets/thumbnail/thumbnail_primary.png','music_bed':'assets/music_bed.mp3','settings':{'width':1920,'height':1080,'fps':30,'voice_speed':1.2,'voice_gain_db':10.0,'broll_clip_max_seconds':5.5,'insert_fade_seconds':0.5,'music_volume_db':-35.0,'audio_rate':44100,'audio_channels':2,'min_duration_seconds':280,'max_duration_seconds':900},'upload':{'title':'Why Every Manchester United Rebuild Fails','description':'Michael Carrick genuinely rescued Manchester United last season. So why has the same team opened 2026/27 with five points from five? This film separates the tactical symptoms from the deeper rebuild problem.\n\nResearch cutoff: 21 September 2026. Tactical diagrams are schematic illustrations, not tracking data.\n\n#ManchesterUnited #PremierLeague #FootballTactics','tags':['Manchester United','Michael Carrick','Premier League','football tactics','football analysis'],'category':'17','privacy':'private'},'captions':{'enabled':True,'fontname':'Arial','font_size':54,'primary_color':'&H00FFFFFF','outline_color':'&H00000000','back_color':'&H64000000','outline':4,'shadow':1,'alignment':2,'margin_l':60,'margin_r':60,'margin_v':66,'group_size':4},'sound_effects':[],'research_checks':{'scoreline_verified':True,'match_number_verified':True,'records_verified':True,'availability_verified':True,'source_urls_recorded':True},'sections':sections}
(P/'long_form_project.json').write_text(json.dumps(cfg,indent=2),encoding='utf-8')
